projects:
  everydb:
    type: library
    model: virion
    path: everydb
    libs:
      - src: poggit/libasynql/libasynql
        version: ^2.0
        branch: "*"
  everydb-example:
    path: example
    libs:
      - src: /everydb
        version: ^1.0
